services:
  - type: web
    name: langflow-tutor
    env: python
    buildCommand: poetry install
    startCommand: langflow run --host 0.0.0.0 --port 7860
    pythonVersion: 3.10.13
    plan: free
    region: oregon
    build:
      cache: false
